// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upbmevgrfouuctsdngla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwYm1ldmdyZm91dWN0c2RuZ2xhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODEzNjcsImV4cCI6MjA3MjQ1NzM2N30.ASFdw4lLWdf3Ssja4ZSHNdcUTlAqq1oml_BseVVNhXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});